apiVersion: v1
kind: Service
metadata:
  name: eda-postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: eda
    comp: postgres
status:
  loadBalancer: {}
