[allowlist]
description = "Global Allowlist"

paths = [
    '''tests\/unit\/data''',
    '''tools\/docker\/redis-tls''',
    '''tests\/integration\/api\/test_event_stream_ecdsa.py''',
    '''tools\/docker\/nginx\/certs''',
    '''tools\/docker\/postgres_ssl_config\/certs''',
] # Ignore based on any subset of the file path
