apiVersion: apps/v1
kind: Deployment
metadata:
  name: eda-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eda
      comp: redis
  strategy: {}
  template:
    metadata:
      labels:
        app: eda
        comp: redis
    spec:
      containers:
        - env: []
          image: docker.io/library/redis:6
          name: redis
          ports:
            - containerPort: 6379
          resources: {}
          volumeMounts:
            - readOnly: false
              mountPath: /data
              name: 'eda-redis-data'
      restartPolicy: Always
      volumes:
        - name: eda-redis-data
          emptyDir: {}
status: {}
