services:
  api:
    image: 'localhost/aap-eda'
    build:
      context: ../../
      dockerfile: tools/docker/Dockerfile
    environment:
      EDA_DB_HOST: 'postgres'
      EDA_MQ_HOST: 'redis'
    command:
      - /bin/bash
      - -c
      - aap-eda-manage migrate
        && aap-eda-manage runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - '../../:/app/src'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ 'CMD', 'curl', '-q', 'http://localhost:8000/_healthz' ]
      interval: 30s
      timeout: 5s
      retries: 10

  postgres:
    image: 'docker.io/library/postgres:13'
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: eda
    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c log_statement=${PG_LOG_STATEMENT:-none}
    ports:
      - '5432:5432'
    volumes:
      - "./postgres/postgresql.conf:/etc/postgresql/postgresql.conf:z"
      - "./postgres/initdb.d:/docker-entrypoint-initdb.d:z"
      - "./postgres/conf.d:/etc/postgresql/conf.d:z"
      - 'postgres_data:/var/lib/postgresql/data'
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres' ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  worker:
    image: 'localhost/aap-eda'
    environment:
      EDA_DB_HOST: 'postgres'
      EDA_MQ_HOST: 'redis'
    command: ['aap-eda-manage', 'rqworker', '--worker-class', 'aap_eda.tasking.Worker']
    volumes:
      - '../../:/app/src'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  redis:
    image: 'docker.io/library/redis:7'
    ports:
      - '6379:6379'
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  postgres_data: {}
